version: "3.8"

services:
  frontend:
    build: .
    container_name: frontend
    ports:
      - "3000:3000"
    networks:
      - library-network
    restart: unless-stopped

networks:
  library-network:
    external: true
